version: '3.8'
services:
  frontend:
    container_name: todoappweb-v1
    image: todoappweb-v1
    build:
      context: .
      target: production
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start