version: "3.8"
services:
    nginx:
        container_name: react-app-ether-2042511demo1
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
        networks:
            - app-network    

#Docker Networks
networks:
  app-network:
    driver: bridge